CREATE TABLE IF NOT EXISTS applications (app_ref varchar(20) NOT NULL,
council_id int(2) NOT NULL,
received_date date DEFAULT NULL,
decision_date date DEFAULT NULL,
url text DEFAULT NULL,
address text DEFAULT NULL,
address1 text DEFAULT NULL,
address2 text DEFAULT NULL,
address3 text DEFAULT NULL,
address4 text DEFAULT NULL,
applicant text DEFAULT NULL,
applicant1 text DEFAULT NULL,
applicant2 text DEFAULT NULL,
applicant3 text DEFAULT NULL,
details text DEFAULT NULL,
decision text DEFAULT NULL,
status text DEFAULT NULL,
lat varchar(25) DEFAULT NULL,
lng varchar(25) DEFAULT NULL,
coordinates varchar(50) DEFAULT NULL,
tweet_id varchar(25) DEFAULT NULL,
KEY council_id (app_ref,council_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;