CREATE TABLE IF NOT EXISTS `councils` (
  `id` int(2) NOT NULL,
  `name` varchar(100) NOT NULL,
  `county_id` int(2) NOT NULL,
  `short_name` varchar(15) NOT NULL,
  `url` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `councils` (`id`, `name`, `county_id`, `short_name`, `url`) VALUES
(7, 'Carlow County Council', 1, 'Carlow', ''),
(8, 'Cavan County Council', 2, 'Cavan', ''),
(9, 'Clare County Council', 3, 'Clare', ''),
(2, 'Cork City Council', 4, 'CorkCity', 'http://planning.corkcity.ie/idocs/listFiles.aspx?catalog=planning&id='),
(10, 'Cork County Council', 4, 'CorkCo', ''),
(14, 'Donegal County Council', 5, 'Donegal', ''),
(3, 'Dublin City Council', 6, 'DublinCity', ''),
(16, 'Dun Laoghaire Rathdown County Council', 6, 'DunLaoghaire', ''),
(17, 'Fingal County Council', 6, 'Fingal', ''),
(4, 'Galway City Council', 7, 'GalwayCity', ''),
(18, 'Galway County Council', 7, 'GalwayCo', ''),
(19, 'Kerry County Council', 8, 'Kerry', ''),
(20, 'Kildare County Council', 9, 'Kildare', ''),
(21, 'Kilkenny County Council', 10, 'Kilkenny', ''),
(22, 'Laois County Council', 11, 'Laois', 'http://www.laois.ie/idocs/listFiles.aspx?catalog=planning&id='),
(23, 'Leitrim County Council', 12, 'Leitrim', ''),
(5, 'Limerick City Council', 13, 'LimerickCity', ''),
(24, 'Limerick County Council', 13, 'LimerickCo', ''),
(25, 'Longford County Council', 14, 'Longford', ''),
(26, 'Louth County Council', 15, 'Louth', ''),
(27, 'Mayo County Council', 16, 'Mayo', ''),
(28, 'Meath County Council', 17, 'Meath', ''),
(29, 'Monaghan County Council', 18, 'Monaghan', ''),
(33, 'North Tipperary County Council', 22, 'NTipperary', ''),
(30, 'Offaly County Council', 19, 'Offaly', ''),
(31, 'Roscommon County Council', 20, 'Roscommon', ''),
(32, 'Sligo County Council', 21, 'Sligo', ''),
(15, 'South Dublin County Council', 6, 'SouthDublin', ''),
(34, 'South Tipperary County Council', 22, 'STipperary', ''),
(6, 'Waterford City Council', 23, 'Waterford', 'http://www.waterfordcity.ie/idocsweb/listFiles.aspx?catalog=planning&id='),
(35, 'Waterford County Council', 23, 'WaterfordCo', 'http://193.178.2.69/idocsweb/listFiles.aspx?catalog=planning&id='),
(36, 'Westmeath County Council', 17, 'Westmeath', ''),
(37, 'Wexford County Council', 25, 'Wexford', ''),
(38, 'Wicklow County Council', 26, 'Wicklow', ''),
(39, 'Letterkenny Council', 5, 'Letterkenny', ''),
(40, 'Bundoran Town Council', 5, 'Bundoran', ''),
(41, 'Buncrana Town Council', 5, 'Buncrana', '');
